version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: "UTC"
      MARIADB_ROOT_PASSWORD: cheolcheol

  mariadb-viewer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cheolcheol
      TZ: "UTC"

  mongo-viewer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: cheolcheol
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:cheolcheol@mongo:27017/
    depends_on:
      - mongo

  storage:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z.fips
    restart: always
    command:  server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    ports:
      - 9000:9000 # service
      - 9001:9001 # console



#  redis:
#    image: redis:6.2.7
#    restart: always
#    ports:
#      - 6379:6379
